### ISSUE TITLE
Zoom horizontal on all plots on/off

### ISSUE THREAD

**Issue by mrlarsendk** [PX4/flight_review#281] opened 2024-06-12 05:53 UTC
I would really love to have the ability to lock zoom on all plots such that when I zoom in time on one plot, I get the exact same time frame in all other plots.

**Comment by bkueng** [comment] 2024-06-25 12:23
Indeed that would be useful.
We just need to check if the browser and server can handle it, because it will trigger many update requests when zooming in all plots at the same time.

**Comment by bkueng** [comment] 2024-12-16 08:00
Duplicate of https://github.com/PX4/flight_review/issues/223

**Closed by bkueng** 2024-12-16 08:00 UTC
